name: Özellik önerisi
description: Yeni bir fikir veya iyileştirme
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Hangi sorunu çözüyor?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Öneri
  - type: dropdown
    id: contribute
    attributes:
      label: Bunu kendiniz geliştirmek ister misiniz?
      options: ["Evet", "Yardım ile", "Hayır"]
